### ISSUE TITLE
Demos don't actually work in other browsers

### ISSUE THREAD

**Issue by domenic** [WICG/virtual-scroller#180]
The use of private field syntax in particular causes them to break. It's probably worth just switching everything to underscores, since the demos are getting to be so effective at illustrating performance differences.

**Comment by fergald** [comment]
Firefox barfs on fields: `SyntaxError: fields are not currently supported    fps-display.mjs:22:2`.

```js
export class FpsDisplay extends HTMLElement {
  _lastTime = null;
  _fps;
```

**Comment by fergald** [comment]
@domenic can you check safari and edge for me?

**Comment by domenic** [comment]
Let's close this and reopen in fergald/virtual-scroller-demos as necessary.
