### ISSUE TITLE
Exploratory findings from sticky.html demo

### ISSUE THREAD

**Issue by chrishtr** [WICG/virtual-scroller#184]
@vmpstr and I did some investigation together today on the [sticky demo](https://wicg.github.io/virtual-scroller/demo/sticky.html). Our findings:

1. With the "divs" version, changing to and from the [compact mode](https://github.com/WICG/virtual-scroller/pull/182) was about 120ms on my beefy Linux box. With virtual-scrollers, it was about 20ms. Better, but still not so great. We suspect that this may be slowed down by needing to do self-rendering (style, layout, etc) on all of the locked roots.

Next up would be to compare against a version that has display:none rather than lock for things offscreen to compare.

**Comment by domenic** [comment]
This seems like it'd be best on the Chromium repo, as it won't impact the spec or demo? (I already find it a bit troublesome to do the demo development in the explainer/spec repo, but ah well.)

**Comment by fergald** [comment]
I think it is very active (as it is now) it's weird. Maybe best to split of
the repos?

**Comment by domenic** [comment]
Let's close this and reopen in fergald/virtual-scroller-demos or the Chromium bug tracker as necessary.
