### ISSUE TITLE
 Does it support recursive generation?

### ISSUE THREAD

**Issue by xiaogaofudao** [WICG/virtual-scroller#187]
such as:
```
<virtual-scroller id='scroller'>
    <div class="node">
        <div class="content">....</div>
        <div class="children">
            <div class="node">
                <div class="content">....</div>
            </div>
            <div class="node">
                <div class="content">....</div>
            </div>
        </div>
    </div>
    <div class="node">
        <div class="content">....</div>
        <div class="children">
            <div class="node">
                <div class="content">....</div>
            </div>
            <div class="node">
                <div class="content">....</div>
            </div>
        </div>
    </div>
</virtual-scroller>

**Comment by fergald** [comment]
I'm not exactly sure what you mean but I can tell you that the content above should look "normal" and the immediate children of the `virtual-scroller` may be display-locked. If you're wondering whether some of the lower descendants would also be display-locked, that is not the intention, only the direct children are locked/unlocked but you can nest scrollers, see this demo: https://wicg.github.io/virtual-scroller/demo/sticky.html

As for what it will look like, it should that

```html
<virtual-scroller>
  any kind of content
</virtual-scroller>
```

will look exactly the same as

```html
<style>
  .virtual-scroller > * { contain: style layout }
</style>
<div class="virtual-scroller">
  any kind of content
</div>
```

**Comment by xiaogaofudao** [comment]
i am confused about the difference between virtual-scroller and virtual-content. which one is better
and  virtual-content cannot work fine when "Experimental Web Platform features" (from chrome://flags) is disabled.

**Comment by fergald** [comment]
virtual-content is an old prototype name. virtual scroller is available as an experimental feature in chrome. See the bottom of 

https://github.com/WICG/virtual-scroller/blob/master/README.md

for instructions on how to try it out. If you find issues with chrome's implementation (please make sure you are using the latestt canary build) please file bug against chrome.
