### ISSUE TITLE
sticky.html demo, "divs" on ToT Chromium doesn't work properly

### ISSUE THREAD

**Issue by vmpstr** [WICG/virtual-scroller#188]
Hi,

I'm loading Chromium with the flags listed in the README, and running https://wicg.github.io/virtual-scroller/demo/sticky.html.  If I toggle to the div implementation, and scroll down, after some point all of the items are blank.

I can't really tell _why_ they are blank..

**Comment by fergald** [comment]
This is a bug in chrome's impl https://crbug.com/1000518
