### ISSUE TITLE
Move demos to another repository; leave this for the specification

### ISSUE THREAD

**Issue by domenic** [WICG/virtual-scroller#189]
The demos are undergoing such active development, and I am afraid of overloading the 83 people who have signed up to get emailed for every piece of activity on this repository. (I.e. the GitHub watchers.)

It's also tricky because the demos are often exposing browser-specific issues (either in Chrome's display locking/virtual scroller implementation, or things like other browsers not supporting class fields) and so we often end up filing issues that aren't even issues with the demos themselves, but instead eventually end up being filed on a browser.

I think we should consider moving them.

**Comment by fergald** [comment]
Makes sense. So another WICG repo? If so, can you set that up?

>

**Comment by domenic** [comment]
Since these are not web standards or explainers, I don't think WICG is an appropriate home. Personal repos, or maybe GoogleChromeLabs, makes the most sense to me.
