### ISSUE TITLE
Multicolumn virtual-scroller support

### ISSUE THREAD

**Issue by vmpstr** [WICG/virtual-scroller#191]
Not sure if this falls under more "exotic" layouts, but currently the approach we're taking with virtual-scroller implementation doesn't work with multicolumn layouts. 

Specifically, consider the following (as run on Chrome's implementation):

```html
<style>
#scroller {
  height: 500px;
  width: max-content;
  overflow-y: scroll;
}
#container {
  width: 300px;
  columns: 2;
}
.item {
  width: 130px;
  height: 300px;
  border: 1px solid black;
  background: lightblue;
  contain: style layout;
  break-inside: avoid;
}
</style>

<div id=scroller>
  <div id=container>
    <virtual-scroller>
      <div class=item>item 0</div>
      <div class=item>item 1</div>
      <div class=item>item 2</div>
      <div class=item>item 3</div>
      <div class=item>item 4</div>
      <div class=item>item 5</div>
      <div class=item>item 6</div>
      <div class=item>item 7</div>
      <div class=item>item 8</div>
      <div class=item>item 9</div>
    </virtual-scroller>
  </div>
</div>

<script type=module>
import('std:elements/virtual-scroller');
</script>
```

The second column is visible but locked. I think due to the fact that we're doing a binary search and determine a single visible range, we end up locking on-screen content. I don't think there's a way to do this with a single range in general and it would have to depend on intersection observer pretty directly. Filing this as just an FYI.

**Comment by fergald** [comment]
I don't think is supportable in any implementation. The intention is to support layouts that are in some sense monotonic along some axis (it's still a bit unclear what the definition of monotonic would be, perhaps we can be as loose as "all pixels of Item(N+1) are greater than at least one pixel of Item(N)")

Consider changing this line

```html
      <div style="height:2000px" class=item>item 2</div>
```

now Item 3 is top of column 2 but we cannot know this without rendering Item 2. Even worse, adjusting the size of the last item

```html
      <div style="height:2000px" class=item>item 9</div>
```

completely changes how many items end up in the first column, and if we render lazily, we don't find out until far too late - we assume it's 4 and 4 and end up with a massive blank space on the left running down the side of item 9.

I will update the explainer to mention them.

**Comment by domenic** [comment]
I kind of thought that at our brainstorming meeting many months ago we had some approach that would work for non-monotonic layouts. I vaguely recall @chrishtr pushing for it a bit?

**Comment by chrishtr** [comment]
@domenic Yes, I did argue that placing an IntersectionObserver on all chunks would work for "all" layouts, and I still think that. For elements which are fragmented across columns, the bounding rect input to IntersectionObserver calculations will be the bounding box of the fragments. In some cases (e.g. very tall columns and an element fragmented across the bottom of one column and the top of the next) this will be an inaccurate representation, but it does *work*, in the sense that the result will be correct.

**Comment by fergald** [comment]
That would work but would require that we allow the layout engine to layout
_all_ of the locked items and that seems to have performance problems.
