### ISSUE TITLE
[traditional-virtualization] What about lists that could go on infinitely back?

### ISSUE THREAD

**Issue by isiahmeadows** [WICG/virtual-scroller#194]
Suppose you used this to implement a year scroller, and you wanted to have it be able to cycle back infinitely far. So far, it doesn't appear such functionality exists, because it requires a length, and if you don't have a start, you can't have a length.

**Comment by fergald** [comment]
As with #195, this branch is not being maintained. In the new proposal, you just add content to the DOM, adding at the bottom if you scroll down, adding at the top if you scroll up. E.g. the load-more demo here

https://fergald.github.io/virtual-scroller-demos/demo/

(it works with/without virtual-scroller enabled in chrome, however if it's not enabled the demo will not perform like a virtual-scroller).
