### ISSUE TITLE
The Project is Stoped ??

### ISSUE THREAD

**Issue by FeehGb** [WICG/virtual-scroller#201]
**This project does not have any update, it is stoped or discontinued.**

**Comment by fergald** [comment]
Yes, there was a [prototype](https://chromium.googlesource.com/chromium/src/+/3dcfb5b3613e35f932d1aaa12f35b03010ba92bd/third_party/blink/renderer/core/script/resources/layered_api/elements/virtual-scroller) but work has stopped and there is currently no plan to go forward (it has been deleted). It would need to be updated to use `content-visibility` which where the CSS stuff finally ended up. There's no technical obstacle to continuing it was a resource and priority decision.
