### ISSUE TITLE
How to measure the performance of virtual scrolling in a production environment？

### ISSUE THREAD

**Issue by lwxsanshui** [WICG/virtual-scroller#202]
In fact, I can view the local performance through the FPS tool in devtools. But how do I know the actual performance of users in the production environment

**Comment by fergald** [comment]
There are APIs like https://developers.google.com/web/updates/2014/11/frame-timing-api which would allow you to record how you site is performing in the wild, I assume there are toolkits built around them but I do not know them personally.
