### ISSUE TITLE
Why is it dead?

### ISSUE THREAD

**Issue by brunnerh** [WICG/virtual-scroller#203]
> This project is no longer being actively developed.

**Comment by varna** [comment]
I assume...
https://web.dev/content-visibility/

**Comment by fergald** [comment]
Yeah, virtual-scroller was a test-bed for a lot of content visibility but the scroller itself is no longer actively developed.

**Comment by Malvoz** [comment]
I'd be great to add an explanation for this under https://github.com/WICG/virtual-scroller#current-status. And afterwards potentially archive this repo?
